name: social-network-otus

services:
  backend-main:
    container_name: backend-main
    ports:
      - 8090:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
    build:
      context: .
      dockerfile: Applications/Backend/MainApi/Dockerfile
    environment:
      - ConnectionStrings__DialogService=http://backend-dialog:8080/api/dialog
      - Postgres__ConnectionStrings__Master=Username=user;Password=password;Server=host.docker.internal;Port=5432;Database=postgres;
      - Postgres__ConnectionStrings__Replicas=Server=host.docker.internal;Port=4080;Username=user;Password=password;Database=postgres;
      - Postgres__ConnectionStrings__Shards__0=Username=user;Password=password;Server=host.docker.internal;Port=5432;Database=postgres;
      - RedisOptions__Endpoint=host.docker.internal:8031
      - Kafka__BootstrapServers=host.docker.internal:9092
    networks:
      - social-network-otus-network

  backend-dialog-1:
    container_name: backend-dialog-1
    ports:
      - 8095:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
    build:
      context: .
      dockerfile: Applications/Backend/DialogApi/Dockerfile
    environment:
      - ConnectionStrings__UserService=http://backend-main:8080/api/user
      - Tarantool__Host=host.docker.internal
      - Tarantool__Port=3301
      - Application__ServerName=backend-dialog-1
    networks:
      - social-network-otus-network

  backend-dialog-2:
    container_name: backend-dialog-2
    ports:
      - 8096:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
    build:
      context: .
      dockerfile: Applications/Backend/DialogApi/Dockerfile
    environment:
      - ConnectionStrings__UserService=http://backend-main:8080/api/user
      - Tarantool__Host=host.docker.internal
      - Tarantool__Port=3301
      - Application__ServerName=backend-dialog-2
    networks:
      - social-network-otus-network

networks:
  social-network-otus-network:
    driver: bridge
