name: social-network-otus

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./docker/postgresql/:/var/lib/postgresql/data/
    ports:
      - 5434:5432
    restart: always
    environment:
      PGPORT: 5434
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    networks:
      - dev

  redis:
    image: redis
    container_name: redis
    environment:
      ALLOW_EMPTY_PASSWORD: TRUE
    command:
      --port 6380
    restart: always
    ports:
      - 6380:6380
    networks:
      - dev

  backend:
    container_name: backend
    depends_on:
      - postgres
      - redis
    ports:
      - 8080:8080
    restart: always
    build:
      context: .
      dockerfile: Applications/Backend/MainApi/Dockerfile
    environment:
      - Postgres__ConnectionStrings__Master=Username=postgres;Password=password;Server=postgres;Port=5432;Database=postgres;
      - Postgres__ConnectionStrings__Replicas__0=Username=postgres;Password=password;Server=postgres;Port=5432;Database=postgres;
      - Postgres__ConnectionStrings__Replicas__1=Username=postgres;Password=password;Server=postgres;Port=5432;Database=postgres;
      - Postgres__ConnectionStrings__Shards__0=Username=postgres;Password=password;Server=postgres;Port=5432;Database=postgres;
      - RedisOptions__Endpoint=redis:6380
    networks:
      - dev



networks:
  dev:
    driver: bridge
