version: '3.9'

name: postgres-dev

services:
  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "main_db"
      POSTGRES_USER: "main_user"
      POSTGRES_PASSWORD: "main_password"
    